### ISSUE TITLE
Qt İmplementation

### ISSUE THREAD

**Issue by anton-dutov** [cbor/cbor.github.io#15]
Please add link to Qt İmplementation
https://github.com/anton-dutov/cbor-qt

**Comment by cabo** [comment]
Thank you!  Example code for half-size floating points is in the RFC; this should be easy to add at least to the decoder (bonus points for the encoder :-).

**Comment by cabo** [comment]
Please tell me if the text linking to the Qt implementation is correct or something should be added/removed.

**Comment by anton-dutov** [comment]
>Thank you! Example code for half-size floating points is in the RFC; this should be easy to add at least to the decoder (bonus points for the encoder :-)

Float decoding already present just encoding not implemented, i'll fix readme soon.

> Please tell me if the text linking to the Qt implementation is correct or something should be added/removed.
Thank you.
