### ISSUE TITLE
Add flunn as Python implementation 

### ISSUE THREAD

**Issue by funny-falcon** [cbor/cbor.github.io#18]
I've forked flynn and and fixes some compatibility issues and have made some refactoring.
https://pypi.python.org/pypi/flunn

**Comment by cabo** [comment]
Thanks!  I have added it.  Is work continuing on this fork?

**Comment by funny-falcon** [comment]
No, but flunn is still a bit ahead of flynn.

**Comment by cabo** [comment]
In any case, flunn is included now, so I'm closing this issue.
