### ISSUE TITLE
another implementation: lua-ConciseSerialization

### ISSUE THREAD

**Issue by fperrad** [cbor/cbor.github.io#23]
lua-ConciseSerialization is a pure Lua implementation of CBOR.

Install via `luarocks`

See http://fperrad.github.io/lua-ConciseSerialization/

**Comment by fperrad** [comment]
See https://github.com/fperrad/lua-ConciseSerialization/blob/master/docs/cbor.md#data-conversion and https://github.com/fperrad/lua-ConciseSerialization/blob/master/docs/cbor.md#set_array-str-

I've already did the same thing with https://fperrad.github.io/lua-MessagePack/

**Comment by cabo** [comment]
Ah, right.  (You probably don't mean "greater than 1", though :-)

**Comment by fperrad** [comment]
It is intentional, Lua arrays are 1-based.
See https://en.wikipedia.org/wiki/Lua_(programming_language)#As_array

**Comment by cabo** [comment]
Sure, but "A Lua table is converted into a CBOR array only if all the keys are composed of positive integers greater than 1, [...]." means that any table that has an element with an index of 1 (i.e., most array-like data) is not converted to a CBOR array.  I don't think that is what you mean.

**Comment by fperrad** [comment]
Right, `composed of positive integers greater or equal than 1`
or `composed of strictly positive integers`

**Comment by cabo** [comment]
(Your docs still seem to say "positive integers greater than 1, ".)
Closing this issue now; thanks again for the pointer.
