### ISSUE TITLE
Skip-scan Java implementation

### ISSUE THREAD

**Issue by noctarius** [cbor/cbor.github.io#24]
Hey guys,

please add my skip-scan parser implementation and fluent data builder to the implementation list. It is build in Java https://github.com/noctarius/borabora.

Documentation and first EA upcoming :)

Thanks,
Chris

**Comment by cabo** [comment]
Thanks for the pointer! Added it.  

A bit of documentation for borabora would indeed be nice :-)

I'd like to learn more about the application you have in mind for this.

**Comment by noctarius** [comment]
Yeah documentation needed and currently prototyping a mutation API, which does match-copy-replace since in-place mutation. I also play around with integration of a GraphQL runtime to "query" only the interesting pieces.

In general, CBOR is an amazing data format for exactly the skip-scan parsing solution! Thanks for this amazing piece of work! :)

Since I think we're in the same timezone, talking about it is easy. I'm already using it for quite a neat analytical use case. You can reach me with the email address in my profile.

PS: Not sure how it works, sent in 2 proposals for additional tags quite a while ago (IETF), they seem to have fated :D

**Comment by cabo** [comment]
In any case, please tell me if the text linking to the implementation is correct or something should be added/removed.
