### ISSUE TITLE
JSON for Modern C++ 2.0.9 supports CBOR

### ISSUE THREAD

**Issue by nlohmann** [cbor/cbor.github.io#25]
The [latest release](https://github.com/nlohmann/json/releases/tag/v2.0.9) of [JSON for Modern C++](https://github.com/nlohmann/json) - a header-only C++ library that aims to promote JSON to a first-class data type in C++11 - now supports CBOR as (de)serialization format.

Examples for the usage:
- deserialization: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a832e482e6248823977628fefa3d780d1.html#a832e482e6248823977628fefa3d780d1
- serialization: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a98b7780376d6b23fb04bd3cb29594b4b.html#a98b7780376d6b23fb04bd3cb29594b4b

It would be great if you could list us in the [implementation section](http://cbor.io/impls.html) of your website. Furthermore, any feedback is greatly appreciated.

**Comment by cabo** [comment]
Thank you for the pointer!

Do you plan to implement any of the parts of CBOR where the generic data model extends that of JSON?  E.g., byte strings, non-text-string map keys, tags, simple values beyond null/false/true?

It would be nice to use your library to implement COSE and CWTs.

**Comment by nlohmann** [comment]
Currently, there is no support beyond JSON planned. We allow any JSON value to be serialized to CBOR and to deserialized them again. There was some discussion regarding byte strings, but we decided not to implement different encoding schemes.

May I ask what COSE and CWTs are?

**Comment by cabo** [comment]
COSE is CBOR Object Signing and Encryption (as with JOSE, but benefitting from the more extensive generic data model of CBOR).  CWTs are JWTs using COSE.  COSE is pretty much done in the IETF (RFC soon; see https://tools.ietf.org/html/draft-ietf-cose-msg-24 for now; CWTs still require a little bit of work.  These structures are the basis of secure low-resource IoT.

**Comment by cabo** [comment]
In any case, please tell me if the text linking to your implementation is correct or something should be added/removed.

**Comment by nlohmann** [comment]
You could link to https://github.com/nlohmann/json when mentioning the name "JSON for Modern C++" and to https://github.com/nlohmann/json#binary-formats-cbor-and-messagepack with the "Details" button.

**Comment by cabo** [comment]
Good idea; done.

**Comment by nlohmann** [comment]
Thanks a lot!
