### ISSUE TITLE
cbor.io is accessible via HTTPS but the cert isn't right (github.io issue)

### ISSUE THREAD

**Issue by durka** [cbor/cbor.github.io#29]
Chrome throws up a security warning because the SSL certificate for cbor.io is registered to a.ssl.fastly.net.

**Comment by shoeper** [comment]
Afaik cbor.io is a Github Page. Not sure if it is possible to either upload a propriate certificate or disable SSL for the page.

**Comment by cabo** [comment]
Right.  I could cloudflare the page, but then I'm not sure what the point of HTTPS access to the information here is in the first place.

**Comment by durka** [comment]
Yeah, I'll send a PR to the linking page instead.

**Comment by lgarron** [comment]
GitHub Pages now supports HTTPS directly: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Would it be possible to turn this on now? :-D

**Comment by lgarron** [comment]
Ahoy! It seems that `cbor.io` doesn't have an automatically provisioned certificate because it's pointing at old Pages IPs:

    > dig -t A cbor.io
    ...
    cbor.io.    300 IN  A 192.30.252.154
    cbor.io.    300 IN  A 192.30.252.153

Could you either replace this with a `CNAME` entry of `cbor.github.io`, or update the set of A records to the four IP addresses listed at https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

**Comment by lgarron** [comment]
@cabo: Any chance you'd be able to change the DNS records as above?

**Comment by cabo** [comment]
Will look at it this weekend.  I'd love to know why people think this is a good use of my time.

**Comment by KOLANICH** [comment]
Try disabling and then enabling TLS in GH-pages settings first.

**Comment by JeremyRand** [comment]
Any news on this?

**Comment by lgarron** [comment]
FWIW, HTTPS is working now!

I would recommend the "Force HTTPS" setting and then call it a day for now. :-D

**Comment by cabo** [comment]
Works for me, too.  Thanks for nudging me.  Closing ticket now.
