### ISSUE TITLE
List cyborg as a Java library

### ISSUE THREAD

**Issue by dwaite** [cbor/cbor.github.io#31]
I've been working on a Java library called cyborg, at https://github.com/dwaite/cyborg.

Additional information on the library:

The initial layer 'electrode' works as a tokenizer and supports stream-based parsing and generation. I am using it in multiple related projects to read and write data with simple schemas. I wanted more flexibility than you typically would get with a library-dictated object model such as with XML or JSON Java tooling, as I thought these didn't pair well with CBOR's richer core data type or with extensible semantic tagging.

I hope to eventually have layers on top for translation to and from other formats, as well as a potential eventual object mapper to allow one to convert Java objects to and from CBOR.

I currently consider the library as in alpha, and am targeting an initial beta release (with binary builds submitted to the maven central repository) on June 10th.

**Comment by cabo** [comment]
Hi David,

is this project moving forward?  I only did a cursory examination, but it seems some documentation on how to use the low-level components would help.

**Comment by cabo** [comment]
Closing this for now, as the link is on the page
