### ISSUE TITLE
GoldFish - Extremely fast CBOR (and JSON) lib

### ISSUE THREAD

**Issue by thongpv3** [cbor/cbor.github.io#35]
https://github.com/OneNoteDev/GoldFish - "JSON/CBOR streaming library, without using memory, like a GoldFish"

I tested in my machine, CBOR parsing performance is 968MB/s (compiled with GCC 7.1). It is 2.5 times faster than tinycbor in deserialize cbor.

I hope you can add it into http://cbor.io/impls.html

**Comment by cabo** [comment]
Please have a look and check that I characterized this correctly.
