### ISSUE TITLE
Is there any diagnostic CBOR tools that can analyse defective CBOR payloads?

### ISSUE THREAD

**Issue by mofosyne** [cbor/cbor.github.io#36]
Most cbor tools just simply throws a non informative error message (e.g. cbor.me ).

Is there a CBOR tool that can spit out a diagnostic message that can work out and point out defective parts of the CBOR message?

The ruby cbor diagnostic tool just crashes if it encounter an error.

**Comment by cabo** [comment]
CBOR.me just provides the error messages that cbor-diag generates.
These could, indeed, be a bit more, er, *diagnostic*.

If you have examples for not-quite-CBOR data where cbor-diag was particularly unhelpful, those could help us make some progress in improving the error messages.  (A related question would be how those defective CBOR data came to be — knowledge about that might also be useful in generating better error messages.)

Grüße, Carsten

**Comment by mofosyne** [comment]
Real world example is this. I found that I declared a 4 item array each carrying an array of 2 sub items, but actually inserted 3 subitems.

The way I solved it, was by creating a naieve version of the C CBOR encoder, that directly interprets each code at a "chunk level" like a diagnostic message, but does not care about extra items being inserted incorrectly. (You could make a modified version that would note this and add a `!!warn` message perhaps.

```
83
03
02
83
82
1a
38
70
14
3d
01
19
77
88
82
1a
38
70
14
3e
02
19
ff
00
82
1a
38
70
14
40
02
02
```

**Comment by cabo** [comment]
Please try that example on cbor.me now (you can use

http://cbor.me/?bytes=83(03-02-83(82(1A.3870143D-01)-19.7788-82(1A.3870143E-02)-19.FF.00.82.1A.38.70.14.40.02.02

if you don't have it handy).  I think this is a slightly better solution for data that is too long.

Unfortunately, better handling of data that is *too short* is much harder to implement (but then it is now a bit easier to manually just throw a blob of f7 at the end of your data and see what happens).

**Comment by mofosyne** [comment]
Certainly a step in the right direction. I think thats a good default behaviour to assume first that the message has erroneous extra bytes.

Though I would add an extra parameter, so that if I know that it's actually still long and just want to see how the rest of the messages is seen. It may be nice to add a "naive diagnostic mode" that keeps parsing, even if the result is nonsensical (like the above example I gave).

So cbor.me diagnostic button could have a drop down (or tickbox) saying "strict" vs "naive" mode or something. But again, it might require more work. At least you are able to show how much it was able to parse before corking out.
