### ISSUE TITLE
Implemented one more CBOR parser in C

### ISSUE THREAD

**Issue by vi** [cbor/cbor.github.io#38]
https://github.com/vi/simple_cbor_stream_parse

Although hacky and sketchy, it should be embedded-friendly, as it does not use memory allocations and can limit all numbers to 16 or 32 bits.

Not sure if it is good enough to be listed on cbor.io, but I don't see any other place to submit CBOR implementations to.

**Comment by cabo** [comment]
Thanks!  I put it on the list.  Any more progress on this implementation?

**Comment by vi** [comment]
What is missing there? CBOR writer?

Most listed limitations are by design.
