### ISSUE TITLE
CBOR implementation for Swift

### ISSUE THREAD

**Issue by Hassaniiii** [cbor/cbor.github.io#43]
I have written a library for CBOR on Swift and I have published it on my GitHub. Alongside with more than 30 different automated unit tests, it is being used practically in our project at the moment. It is working very well, and it is very easy to use for iOS projects (it is available and accessible on Cocoapods too).

Vancosys Data Security Inc.: www.vancosys.com
CBORSwift on GitHub: https://github.com/Hassaniiii/CBORSwift

**Comment by cabo** [comment]
Thanks!  Please send status updates whenever you have them.
