### ISSUE TITLE
Yet another one c++ implementation

### ISSUE THREAD

**Issue by serge-klim** [cbor/cbor.github.io#46]
Not sure if  this: https://github.com/serge-klim/bobl  C++ implementation  would be useful to somebody. It's not exactly coder/decoder per se. It is more type based compile time encoders/decoders generator which uses CBOR as one of underlying protocols and its API is similar to recommended:

encoded = CBOR.encode(data) ➔ data = CBOR.decode(encoded) ( auto encoded = bobl::cbor::encode(data); ➔ auto data = bobl::cbor::decode<DataType>(begin(encoded), end(encoded));)

**Comment by cabo** [comment]
This is now mentioned.  Please check and suggest possible changes.  Thank you for the pointer!
