### ISSUE TITLE
Creating a byte string using cbor.me

### ISSUE THREAD

**Issue by tautologyclub** [cbor/cbor.github.io#47]
How do I define a byte string using diagnostic notation using cbor.me? `[0xa, 0xb, 0xc, 0xd]` gives me `# array(4)`.

**Comment by cabo** [comment]
The diagnostic notation for byte strings for what I think you are trying to do is: `h'0a0b0c0d` as in http://cbor.me/?diag=h%270a0b0c0d%27

In CBOR, a byte string is a different construct from an array of integers.

**Comment by tautologyclub** [comment]
tyvm
