### ISSUE TITLE
New Perl CBOR modules: CBOR::Free and CBOR::PP

### ISSUE THREAD

**Issue by FGasper** [cbor/cbor.github.io#50]
Hello,

I’ve written a two new Perl CBOR implementations:
https://metacpan.org/pod/CBOR::Free
https://metacpan.org/pod/CBOR::PP

CBOR::Free is in XS. It’s a bit more restricted in scope relative to CBOR::XS, but it’s got a more permissive license and (unlike CBOR::XS) supports newer Perl versions.

It’s also, in my benchmarks, faster yet than CBOR::XS. :)

CBOR::PP was my first attempt at a CBOR library. I’m releasing it in case it’s of use to someone but anticipate that CBOR::Free will be what pretty much anyone prefers to use.

**Comment by cabo** [comment]
I think I can close this now?  Please check and suggest possible changes.  Thank you for the pointer!
