### ISSUE TITLE
OCaml has CBOR implementations

### ISSUE THREAD

**Issue by jhwoodyatt** [cbor/cbor.github.io#52]
The [OCaml](https://ocaml.org) programming language has a couple of notable CBOR implementations.

- The [cbor](https://opam.ocaml.org/packages/cbor/) package is a minimal and lightweight implementation of just the core CBOR data structures. It encodes and decodes to and from OCaml strings.

- The [orsetto](https://opam.ocaml.org/packages/orsetto/) package is a serialization framework that includes streaming encoders and decoders for both JSON and CBOR.

**Comment by cabo** [comment]
These are now mentioned.  Please check and suggest possible changes.  Thank you for the pointer!

**Comment by jhwoodyatt** [comment]
Thanks!!
