### ISSUE TITLE
Cross-collaboration with JSON5

### ISSUE THREAD

**Issue by DonaldTsang** [cbor/cbor.github.io#53]
Recently there has been a new JSON spec being drafted, might be a good idea to discuss in regards to binary data encodings.
https://github.com/json5/json5/issues/190

**Comment by cabo** [comment]
CBOR has its own diagnostic format derived from JSON (as defined in 
https://tools.ietf.org/html/rfc7049#section-6
with recent extensions documented in
https://tools.ietf.org/html/rfc8610#appendix-G ).
https://tools.ietf.org/html/rfc7049#section-6 also mentions YAML as a text-based format for
representing CBOR data items in configuration files.
I'm not sure that the various recent xjsonx efforts add anything useful to these well-established specifications.

**Comment by DonaldTsang** [comment]
It is good to have some communications in regards to redesigns I think, even if it is unorthodox compared to RFCs
