### ISSUE TITLE
New C# implementation

### ISSUE THREAD

**Issue by mcatanzariti** [cbor/cbor.github.io#54]
Hi,

Please add a CBOR implementation for .Net (C#): 

Dahomey.Cbor
https://github.com/dahomey-technologies/Dahomey.Cbor

Thank you,

Michaël

**Comment by mcatanzariti** [comment]
# Dahomey.Cbor
High-performance CBOR serialization framework for .Net (C#)

## Features
* Serialization/Deserialization from/to Streams, byte buffer
* Object Model
* Mapping to any .Net class
* Extensible Polymorphism support based on discriminator conventions
* Extensible Naming conventions
* Custom converters for not supported types
* [.Net standard 2.0](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md) support

**Comment by cabo** [comment]
This is now mentioned.  Please check and suggest possible changes.  Thank you for the pointer!
