### ISSUE TITLE
Elixir CBOR

### ISSUE THREAD

**Issue by tomciopp** [cbor/cbor.github.io#55]
I've forked and updated your excbor package and was wondering if you could add it to the list of elixir implementations on `cbor.io`.

https://github.com/scalpel-software/cbor

Also, I think you may want to add additional test data for big integers. This area seems to be neglected in the appendix of the RFC.

**Comment by cabo** [comment]
Hi Thomas,

this looks like the rightful heir of excbor -- should I simply replace that with yours?

**Comment by tomciopp** [comment]
That would be fine with me.

**Comment by cabo** [comment]
OK, please check whether the reference is OK and whether you would like anything else mentioned.
