### ISSUE TITLE
C, C++ implementation

### ISSUE THREAD

**Issue by jvermillard** [cbor/cbor.github.io#8]
I think you published a C implementation on github, and there are also an extra couple of good one.
Whould be nice to point to them, because the lack of opensource C implementation can be a show stopper for potential adopters

**Comment by Type1J** [comment]
+1

**Comment by cabo** [comment]
I've added three.  Now what other C/C++ implementations do you want to see mentioned.

**Comment by c-rack** [comment]
There is a new C implementation by @PJK available:
https://github.com/PJK/libcbor

**Comment by PJK** [comment]
Feel free to add it to the list, @cabo :)

Thanks for the mention, @c-rack!

**Comment by cabo** [comment]
Thanks, Constantin and Pavel.
Pointer added.
Just had a first look at the implementation.  Woot!
