### ISSUE TITLE
bad links again ...

### ISSUE THREAD

**Issue by mikejt** [cbor/cbor.github.io#9]
many of the IETF and IANA (and a few other) links are missing the "https://"

**Comment by cabo** [comment]
I'm using http:// links right now, in line with the fact that the entire cbor.io site is not secure.
But maybe I don't understand what you are telling me, after all.

**Comment by mikejt** [comment]
Hmm. Things seem to work fine now that I'm away from hotel WiFi ... Plus now I'm using my iPad, so the whole chain is different. I guess you should close this unless I can reproduce it. 

-- 
There are 3 sorts of people. Those who can count, and those who can't.
http://Michael.JohasTeener.com ... http://www.linkedin.com/in/mjohasteener

**Comment by cabo** [comment]
Ah, hotel WiFi is a known chaos monkey...
Closing this for now.
Thanks anyway for alerting me.
